"""changed products and users

Revision ID: 61a2ca233367
Revises: 807c438e0911
Create Date: 2025-11-19 22:24:19.045748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a2ca233367'
down_revision: Union[str, Sequence[str], None] = '807c438e0911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DECIMAL(precision=16, scale=4), nullable=False))
    # op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=255), nullable=True))
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # op.drop_column('users', 'username')
    # Well, I actually renamed the column
    op.execute('ALTER TABLE users RENAME COLUMN username TO user_name;')    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # op.drop_column('users', 'user_name')
    op.execute('ALTER TABLE users RENAME COLUMN user_name TO username;')
    op.drop_column('products', 'price')
    # description: Mapped[Optional[str]] = mapped_column(VARCHAR(3000))
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),  # What exists now (unlimited VARCHAR)
               type_=sa.VARCHAR(length=3000),  # What we want (VARCHAR(3000))
               existing_nullable=True)
    
    # ### end Alembic commands ###
